INSERT INTO product (id, name, description, price, product_image_id) VALUES
(1,'Grey Puffer Fish','The elegant Grey Puffer Fish','49.99',1),
(2,'Dark Blue White Block Logo','The fashionable Dark Blue White Block Logo','49.99',2),
(3,'Light Grey Puffer Bubbles Fish','This is a fantastic Light Grey Puffer Bubbles Fish','49.99',3),
(4,'White with Varsity Logo','The innovative White with Varsity Logo','29.99',4),
(5,'Lime Green with Cloud Logo','The elegant Lime Green with Cloud Logo','29.99',5),
(6,'Red Puffer Mountain Vista','The cool Red Puffer Mountain Vista','29.99',6),
(7,'Khaki Two Tone Logo','This is a fantastic Khaki Two Tone Logo','29.99',7),
(8,'Blue Kawaii Puffer Fish','The elegant Blue Kawaii Puffer Fish','29.99',8),
(9,'Light Grey Ye Herald Logo','This is a fantastic Light Grey Ye Herald Logo','29.99',9),
(10,'Green Underwater Puffer','Experience the comfort of our Green Underwater Puffer','29.99',10),
(11,'Black Raised Block White Logo','The chic Black Raised Block White Logo','59.99',11),
(12,'Blue Varsity Puffer','The elegant Blue Varsity Puffer','59.99',12),
(13,'Pink Varsity Puffer','The sophisticated Pink Varsity Puffer','59.99',13),
(14,'Red Cloud Puffer','The iconic Red Cloud Puffer','59.99',14),
(15,'Yellow Cloud Puffer','Introducing the new Yellow Cloud Puffer','29.99',15),
(16,'Red Logotype Puffer','Introducing the new Red Logotype Puffer','59.99',16),
(17,'Prison Stripes Puffer','Get the latest Prison Stripes Puffer','59.99',17),
(18,'Puffer Fish on White','Experience the comfort of our Puffer Fish on White','59.99',18),
(19,'Navy Capital P for Puffer','The chic Navy Capital P for Puffer','59.99',19),
(20,'Lime Master of Puffer','The modern Lime Master of Puffer','59.99',20),
(21,'Red Script Puffer','The iconic Red Script Puffer','39.99',21),
(22,'Grey Varsity Puffer','The iconic Grey Varsity Puffer','49.99',22),
(23,'Lime 3D Block Puffer','Get the latest Lime 3D Block Puffer','19.99',23),
(24,'Red Hiding in the Clouds Puffer','The bold Red Hiding in the Clouds Puffer','39.99',24),
(25,'White Mono Puffer Fish','The elegant White Mono Puffer Fish','39.99',25),
(26,'White Serif Puffer','The innovative White Serif Puffer','39.99',26),
(27,'Red Cloud on Top Logo','This is a fantastic Red Cloud on Top Logo','29.99',27),
(28,'Green Under the Sea Puffer Fish','The unique Green Under the Sea Puffer Fish','39.99',28),
(29,'White with Pink Bands Varsity Puffer','This is a fantastic White with Pink Bands Varsity Puffer','39.99',29),
(30,'Red Puffer Double Border','One of our top sellers, the Red Puffer Double Border','39.99',30),
(31,'Grey Puffer in Pink College Fish','The classic Grey Puffer in Pink College Fish','29.99',31),
(32,'Midnight Stretched Long Puffer','Experience the comfort of our Midnight Stretched Long Puffer','39.99',32),
(33,'Green Bubbles the Puffer Fish','The bold Green Bubbles the Puffer Fish','29.99',33),
(34,'Grey Varsity Puffer on White','Check out the stylish Grey Varsity Puffer on White','39.99',34),
(35,'Teal Green White Fluffy Puffer','Introducing the new Teal Green White Fluffy Puffer','19.99',35),
(36,'Orange Tetons Range Puffer','Check out the stylish Orange Tetons Range Puffer','49.99',36),
(37,'Red Half Puffer','Our exclusive Red Half Puffer','39.99',37),
(38,'Green Cutie Puffer Fish','The classic Green Cutie Puffer Fish','39.99',38),
(39,'Established Then Off White Puffer','The bold Established Then Off White Puffer','59.99',39),
(40,'Submerged Puffer in Black','The fashionable Submerged Puffer in Black','39.99',40),
(41,'Green Eagle Puffer','Get the latest Green Eagle Puffer','69.99',41),
(42,'Blue Basics Puffer','The elegant Blue Basics Puffer','19.99',42),
(43,'Salmon Varsity Puffer','The fashionable Salmon Varsity Puffer','39.99',43),
(44,'Orange Puffer Wrapped in a Cloud','The cool Orange Puffer Wrapped in a Cloud','29.99',44),
(45,'Orange 3D Puffed Puffer','The timeless Orange 3D Puffed Puffer','39.99',45),
(46,'Orange Serif Puffer Logo','Introducing the new Orange Serif Puffer Logo','469.99',46),
(47,'Pink Prison Break Puffer','The cool Pink Prison Break Puffer','19.99',47),
(48,'Black Puffer Fish 88','Get the latest Black Puffer Fish 88','39.99',48),
(49,'Turquoise Puffer Outlined','Introducing the new Turquoise Puffer Outlined','29.99',49),
(50,'Teal Puffer Big Shadow','The fashionable Teal Puffer Big Shadow','39.99',50),
(51,'Brown Puffer Underlined','Experience the comfort of our Brown Puffer Underlined','59.99',51),
(52,'Light Blue Puffer Block','The unique Light Blue Puffer Block','69.99',52),
(53,'Forest Green Puffer Lower Shadow','Experience the comfort of our Forest Green Puffer Lower Shadow','39.99',53),
(54,'Magenta with Grey Cloud Puffer','Get the latest Magenta with Grey Cloud Puffer','19.99',54),
(55,'Grey Puffer Fish','The cool Grey Puffer Fish','29.99',55),
(56,'Simply Puffer in White','The unique Simply Puffer in White','39.99',56),
(57,'Magenta Friendly Puffer Cloud','The bold Magenta Friendly Puffer Cloud','49.99',57),
(58,'Submerged Puffer in Forest Green','Introducing the new Submerged Puffer in Forest Green','59.99',58),
(59,'Off White Pink Bands Varsity','The cool Off White Pink Bands Varsity','69.99',59),
(60,'Purple Puffer Classic','The modern Purple Puffer Classic','19.99',60),
(61,'Pink Puffer Skull','The fashionable Pink Puffer Skull','29.99',61),
(62,'Pink Puffer Wolf','The unique Pink Puffer Wolf','39.99',62),
(63,'Pink Mean Fluffy Puffer','The fashionable Pink Mean Fluffy Puffer','49.99',63),
(64,'Pink Puffer SWAT','The unique Pink Puffer SWAT','59.99',64);




